name: skyline-api

services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5400:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:alpine
    restart: unless-stopped
    ports:
      - 6300:6379
    environment:
      REDIS_PASSWORD: password
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
